# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20171023_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='relations',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(related_name='followers', through='member.Relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
